### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by psifertex** [0bs3n/arch-blackfin#1]
Apologies for not replying sooner but can you please trigger a new release? for some reason the current release isn't showing up in the GH release API when I try to add this to the plugin repo using https://github.com/Vector35/community-plugins/blob/master/generate_index.py

Specifically, the steps should be in: https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release

**Comment by 0bs3n** [comment]
Hey, thanks for reaching out. I've created a new release (v0.1.1), please let me know if that works. Otherwise, if you could give me some guidance as to what might be causing the problem I can work toward fixing it, thanks.

In my original release, I had included a compiles .so for the plugin. Perhaps that's what caused the issue, so I've removed it, but let me know if it should be present. All the python plugins in the community repo just have source code included in the release, but I didn't see any other examples of C++ plugins in the community repo and the requirements may be different there.

**Comment by psifertex** [comment]
D'oh -- totally my fault, copy paste failure. Sorry about that! 🤦‍♂️

It's added.
